select * from customer

--what is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as revenue
from customer
group by gender;

--which customers used a discount but still spent more than the average purcahse amount?
select customer_id, purchase_amount
from customer
where discount_applied ='Yes'
and purchase_amount >=(select AVG(purchase_amount)from customer);

--which are the top 5 products with the highest average review ratings?
select item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average product rating"
from customer
group by item_purchased
order by AVG(review_rating) desc
limit 5;

--Compare the average purchase amount between standard and express shipping
select ROUND(AVG(purchase_amount),2) as "Average purchase amount", shipping_type
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

--Do subscribed customers spend more ? compare average spend and total revenue between subs and non subs
select subscription_status,
count(customer_id) as total_customers,
ROUND(avg(purchase_amount),2) as avg_spend,
ROUND(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;


--which 5 products have the highest percentage of purcahses with discount applied?
select item_purchased,
ROUND(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--segment customer into new, returning and loyal based on their total number of previous purcahses and show the count of each segment
with customer_type as (
select customer_id,
previous_purchases
case when previous_purchases = 1 then "New"
when previous_purchases between 2 and 10 then "Returning"
else "Loyal"
end as customer_segment
from customer
)

select customer_segment, count(*) as "Number of customers"
from customer_type
group by customer_segment;

--what are the top 3 most purchased products within each category
with item_count as(
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category,item_purchased
)

select item_rank,category,item_purchased,total_orders
from item_count
where item_rank<=3;

--are customers who are repeat buyers (more than 5 previous purcahses) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

--what is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;